// 協定的唯一來源已搬到 Cinderous SDK（ADR-0370；SDK ADR 0010）：`@cinderous/client/protocol`。
// 這裡照原名轉出，App 其他程式的 import 不必改。要改協定：先改 SDK、發版，再升這裡的相依。
export {
  EK_ANNOUNCE_KIND,
  FS_CAPABILITY,
  FS_CAPABILITY_PQ,
  FS_RETIRED,
  FS_CAPABILITY_MAX_LEN,
  readFsCapability,
  EK_HINT_TAG,
  FS_GRACE_MS,
  FS_ROTATE_INTERVAL_MS,
  shouldRotateFs,
  pruneFsKeys,
  readPin,
  FS_SCHEME_RANK,
  compareFsStrength,
  pinAfterDeclare,
  strongerPin,
  pinOnEvidence,
  pinIsDowngraded,
  EMPTY_FS_FAILURE_LOG,
  FS_PENDING_MAX,
  FS_PENDING_TTL_MS,
  prunePendingFs,
  retainPendingFs,
  recordFsFailure,
  generateEncryptionKey,
  buildEkAnnounce,
  ekAnnounceContent,
  EK_ANNOUNCE_VERSION,
  EK_ANNOUNCE_PQ_VERSION,
  EK_PQ_ANNOUNCE,
  readEkAnnounce,
  withEkHint,
  ekHintOf,
  openWrapWithEks,
  type FsCapability,
  type FsPin,
  type StoredFsPin,
  type FsStrength,
  type FsFailureLog,
  type PendingFsEvent,
  type EncryptionKey,
  type EkAnnounce,
} from "@cinderous/client/protocol";
